// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Winkompass_Mobil.Controllers
{
    public partial class PurchaseController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PurchaseController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PurchaseController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MakePurchaseGet()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakePurchaseGet);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MakePurchase()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakePurchase);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PurchaseController Actions { get { return MVC.Purchase; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Purchase";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Purchase";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string MakePurchaseGet = "MakePurchase";
            public readonly string MakePurchase = "MakePurchase";
            public readonly string PurchaseList = "PurchaseList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string MakePurchaseGet = "MakePurchase";
            public const string MakePurchase = "MakePurchase";
            public const string PurchaseList = "PurchaseList";
        }


        static readonly ActionParamsClass_MakePurchaseGet s_params_MakePurchaseGet = new ActionParamsClass_MakePurchaseGet();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MakePurchaseGet MakePurchaseGetParams { get { return s_params_MakePurchaseGet; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MakePurchaseGet
        {
            public readonly string sup = "sup";
            public readonly string supNo = "supNo";
        }
        static readonly ActionParamsClass_MakePurchase s_params_MakePurchase = new ActionParamsClass_MakePurchase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MakePurchase MakePurchaseParams { get { return s_params_MakePurchase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MakePurchase
        {
            public readonly string reg = "reg";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string MakePurchase = "MakePurchase";
                public readonly string PurchaseList = "PurchaseList";
            }
            public readonly string MakePurchase = "~/Views/Purchase/MakePurchase.cshtml";
            public readonly string PurchaseList = "~/Views/Purchase/PurchaseList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PurchaseController : Winkompass_Mobil.Controllers.PurchaseController
    {
        public T4MVC_PurchaseController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MakePurchaseGetOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sup, string supNo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MakePurchaseGet(string sup, string supNo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakePurchaseGet);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sup", sup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "supNo", supNo);
            MakePurchaseGetOverride(callInfo, sup, supNo);
            return callInfo;
        }

        [NonAction]
        partial void MakePurchaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Winkompass_Mobil.Models.ScanItemModel reg);

        [NonAction]
        public override System.Web.Mvc.ActionResult MakePurchase(Winkompass_Mobil.Models.ScanItemModel reg)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakePurchase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reg", reg);
            MakePurchaseOverride(callInfo, reg);
            return callInfo;
        }

        [NonAction]
        partial void PurchaseListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PurchaseList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PurchaseList);
            PurchaseListOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
