// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Winkompass_Mobil.Controllers
{
    public partial class StorageController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public StorageController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected StorageController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StorageCount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StorageCount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QuickCount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuickCount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Top5()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Top5);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public StorageController Actions { get { return MVC.Storage; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Storage";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Storage";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreateTemplate = "CreateTemplate";
            public readonly string StorageCount = "StorageCount";
            public readonly string StorageList = "StorageList";
            public readonly string QuickCount = "QuickCount";
            public readonly string Top5 = "Top5";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreateTemplate = "CreateTemplate";
            public const string StorageCount = "StorageCount";
            public const string StorageList = "StorageList";
            public const string QuickCount = "QuickCount";
            public const string Top5 = "Top5";
        }


        static readonly ActionParamsClass_CreateTemplate s_params_CreateTemplate = new ActionParamsClass_CreateTemplate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateTemplate CreateTemplateParams { get { return s_params_CreateTemplate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateTemplate
        {
            public readonly string kModel = "kModel";
        }
        static readonly ActionParamsClass_StorageCount s_params_StorageCount = new ActionParamsClass_StorageCount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StorageCount StorageCountParams { get { return s_params_StorageCount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StorageCount
        {
            public readonly string id = "id";
            public readonly string reg = "reg";
        }
        static readonly ActionParamsClass_StorageList s_params_StorageList = new ActionParamsClass_StorageList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StorageList StorageListParams { get { return s_params_StorageList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StorageList
        {
            public readonly string kModel = "kModel";
        }
        static readonly ActionParamsClass_QuickCount s_params_QuickCount = new ActionParamsClass_QuickCount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuickCount QuickCountParams { get { return s_params_QuickCount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuickCount
        {
            public readonly string id = "id";
            public readonly string reg = "reg";
        }
        static readonly ActionParamsClass_Top5 s_params_Top5 = new ActionParamsClass_Top5();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Top5 Top5Params { get { return s_params_Top5; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Top5
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateTemplate = "CreateTemplate";
                public readonly string QuickCount = "QuickCount";
                public readonly string StorageCount = "StorageCount";
                public readonly string StorageList = "StorageList";
                public readonly string StorageListUnlimited = "StorageListUnlimited";
                public readonly string Top5 = "Top5";
            }
            public readonly string CreateTemplate = "~/Views/Storage/CreateTemplate.cshtml";
            public readonly string QuickCount = "~/Views/Storage/QuickCount.cshtml";
            public readonly string StorageCount = "~/Views/Storage/StorageCount.cshtml";
            public readonly string StorageList = "~/Views/Storage/StorageList.cshtml";
            public readonly string StorageListUnlimited = "~/Views/Storage/StorageListUnlimited.cshtml";
            public readonly string Top5 = "~/Views/Storage/Top5.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_StorageController : Winkompass_Mobil.Controllers.StorageController
    {
        public T4MVC_StorageController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateTemplate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTemplate);
            CreateTemplateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Winkompass_Mobil.Models.TemplateModel kModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateTemplate(Winkompass_Mobil.Models.TemplateModel kModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTemplate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "kModel", kModel);
            CreateTemplateOverride(callInfo, kModel);
            return callInfo;
        }

        [NonAction]
        partial void StorageCountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult StorageCount(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StorageCount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            StorageCountOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void StorageCountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, Winkompass_Mobil.Models.ScanItemModel reg);

        [NonAction]
        public override System.Web.Mvc.ActionResult StorageCount(string id, Winkompass_Mobil.Models.ScanItemModel reg)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StorageCount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reg", reg);
            StorageCountOverride(callInfo, id, reg);
            return callInfo;
        }

        [NonAction]
        partial void StorageListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult StorageList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StorageList);
            StorageListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StorageListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Winkompass_Mobil.Models.TemplateModel kModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult StorageList(Winkompass_Mobil.Models.TemplateModel kModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StorageList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "kModel", kModel);
            StorageListOverride(callInfo, kModel);
            return callInfo;
        }

        [NonAction]
        partial void QuickCountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuickCount(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuickCount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QuickCountOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QuickCountOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id, Winkompass_Mobil.Models.ScanItemModel reg);

        [NonAction]
        public override System.Web.Mvc.JsonResult QuickCount(string id, Winkompass_Mobil.Models.ScanItemModel reg)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QuickCount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reg", reg);
            QuickCountOverride(callInfo, id, reg);
            return callInfo;
        }

        [NonAction]
        partial void Top5Override(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Top5(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Top5);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            Top5Override(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
