//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Account1 { get; set; }
        public string Name { get; set; }
        public string Account2 { get; set; }
        public string Name2 { get; set; }
        public string Consolidate { get; set; }
        public byte Type { get; set; }
        public string SetOff { get; set; }
        public string Tax { get; set; }
        public string Currency { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public double Balance { get; set; }
        public double Quantity { get; set; }
        public string Remarks { get; set; }
        public string ReportCode1 { get; set; }
        public string ReportCode2 { get; set; }
        public string ReportCode3 { get; set; }
        public string ReportCode4 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public bool PageBreakBefore { get; set; }
        public short TabTo { get; set; }
        public short Blocked { get; set; }
        public string DefaultText { get; set; }
        public bool StatementPageBreakBefore { get; set; }
        public System.Guid GUID { get; set; }
        public string AccountRight { get; set; }
        public bool TotalAfter { get; set; }
        public bool TimeLinkCost { get; set; }
        public bool TimeLinkPost { get; set; }
    }
}
