//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsBalanceAccount
    {
        public System.Guid ParentGUID { get; set; }
        public long Account { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public long SetOff { get; set; }
        public System.Guid GUID { get; set; }
    }
}
