//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsBalance
    {
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
        public short Year1 { get; set; }
        public short Year1PeriodFrom { get; set; }
        public short Year1PeriodTo { get; set; }
        public short Year2 { get; set; }
        public short Year2PeriodFrom { get; set; }
        public short Year2PeriodTo { get; set; }
        public short ShowZeroAccount { get; set; }
        public short UseDimension { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public short In1000 { get; set; }
        public short InBalance { get; set; }
    }
}
