//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisAccount
    {
        public string TurnOver { get; set; }
        public string VariableCosts { get; set; }
        public string CapacityCosts { get; set; }
        public string Interest { get; set; }
        public string LiquidAssets { get; set; }
        public string Customers { get; set; }
        public string Stock { get; set; }
        public string FixedAssets { get; set; }
        public string Suppliers { get; set; }
        public string PublicDebt { get; set; }
        public string LongTermDebt { get; set; }
        public string NetCapital { get; set; }
        public string CurEarnings { get; set; }
        public System.Guid GUID { get; set; }
    }
}
