//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsciiCode
    {
        public int UnikID { get; set; }
        public short ID { get; set; }
        public short TP { get; set; }
        public short CodePos { get; set; }
        public string Code { get; set; }
    }
}
