//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsciiAvance
    {
        public int UnikID { get; set; }
        public short ID { get; set; }
        public string AvanceCode { get; set; }
        public double AvancePct { get; set; }
    }
}
