//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsciiImp
    {
        public int UnikID { get; set; }
        public string ID { get; set; }
        public string Format { get; set; }
        public bool ColNameheader { get; set; }
        public string CharacterSet { get; set; }
        public string DateTimeFormat { get; set; }
        public string DecimalSymbol { get; set; }
        public short NumberDigits { get; set; }
        public string CurrencySymbol { get; set; }
        public string FileName { get; set; }
        public string Delimiter { get; set; }
        public string AvanceType { get; set; }
        public string AvancePriceListSale { get; set; }
        public string AvancePriceListBye { get; set; }
        public bool IncludeCreate { get; set; }
        public bool IncludeChange { get; set; }
        public bool IncludeDelete { get; set; }
        public bool BookChange { get; set; }
        public string SalesPriceTax { get; set; }
        public string CostPriceTax { get; set; }
        public string AvancePriceType { get; set; }
        public bool DeleteZeros { get; set; }
        public string Description { get; set; }
    }
}
