//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankSetup
    {
        public string BankID { get; set; }
        public string FileName { get; set; }
        public string BankNo { get; set; }
        public string SetOff { get; set; }
        public string LockedBy { get; set; }
        public string RegNo { get; set; }
        public System.Guid GUID { get; set; }
    }
}
