//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCurrency
    {
        public string BankID { get; set; }
        public string Currency { get; set; }
        public byte RateType { get; set; }
        public decimal TerminsNo { get; set; }
        public double Rate { get; set; }
        public System.Guid GUID { get; set; }
    }
}
