//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterialPrintNotAvailable
    {
        public string PrintID { get; set; }
        public string Item { get; set; }
        public double Quantity { get; set; }
        public string Location { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
    }
}
