//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDiscount
    {
        public string CashDiscount1 { get; set; }
        public short ShowInTP { get; set; }
        public string Description { get; set; }
        public short Type { get; set; }
        public short Days { get; set; }
        public double CashDiscountPct { get; set; }
        public short CashDiscountInclTax { get; set; }
        public short CashDiscountInclFee { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
    }
}
