//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string Company1 { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Telex { get; set; }
        public string RegNo { get; set; }
        public string Bank { get; set; }
        public string Giro { get; set; }
        public string TaxNo { get; set; }
        public string Currency { get; set; }
        public float Rate { get; set; }
        public string Consolidate { get; set; }
        public float Percent { get; set; }
        public short DataFormat { get; set; }
        public string Connect { get; set; }
        public string Reports { get; set; }
        public short Checked { get; set; }
        public short Link { get; set; }
        public string Email { get; set; }
        public string InterNet { get; set; }
        public string OldDataBase { get; set; }
        public Nullable<System.DateTime> LastBackUp { get; set; }
        public short BackUpDays { get; set; }
        public string FIKNumber { get; set; }
        public string WinkompasVersion { get; set; }
        public short WinkompasRevision { get; set; }
        public string WinkompasDBInfo { get; set; }
        public string TaxNoForeignSale { get; set; }
        public string PhoneMobil { get; set; }
        public short FileVersion { get; set; }
        public short LastChecked { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
        public System.Guid GUID { get; set; }
        public string BankName { get; set; }
        public string BackgroundImage { get; set; }
        public string StartWebSite { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentArchivePath { get; set; }
    }
}
