//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public string CostCenter1 { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public double CostPrice { get; set; }
        public double Price { get; set; }
        public double Avance { get; set; }
        public byte ProjectLineState { get; set; }
        public System.Guid GUID { get; set; }
        public byte CostCenterType { get; set; }
        public string Grouping { get; set; }
        public short SortOrder { get; set; }
        public byte CostCenterType2 { get; set; }
    }
}
