//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInterestSaldo
    {
        public long RecordID { get; set; }
        public string Customer { get; set; }
        public System.DateTime Date { get; set; }
        public double Balance { get; set; }
        public double Rate { get; set; }
        public double Interest { get; set; }
        public int InterestDays { get; set; }
        public System.Guid GUID { get; set; }
    }
}
