//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReminderCalc
    {
        public string Customer { get; set; }
        public string Currency { get; set; }
        public string Host { get; set; }
        public bool Select { get; set; }
        public double Open { get; set; }
        public double OpenBase { get; set; }
        public double Amount { get; set; }
        public System.Guid GUID { get; set; }
    }
}
