//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInterestCalc
    {
        public string Customer { get; set; }
        public string Host { get; set; }
        public bool Select { get; set; }
        public double CalcBalance { get; set; }
        public double CalcInterest { get; set; }
        public Nullable<System.DateTime> InterestDate { get; set; }
        public double CalcCharge { get; set; }
        public System.Guid GUID { get; set; }
        public double CalcDueBalance { get; set; }
    }
}
