//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReport
    {
        public string Reports { get; set; }
        public string Statement { get; set; }
        public string Quotation { get; set; }
        public string Confirmation { get; set; }
        public string PackingList { get; set; }
        public string Invoice { get; set; }
        public string InterestNote { get; set; }
        public string Remarks { get; set; }
        public string Reminder { get; set; }
        public string Cash { get; set; }
        public string Subscription { get; set; }
        public string StatementAll { get; set; }
        public string CreditNote { get; set; }
        public string CashCreditNote { get; set; }
        public string SubscriptionCreditNote { get; set; }
        public System.Guid GUID { get; set; }
        public string PickList { get; set; }
        public bool EmailGroup { get; set; }
    }
}
