//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Customer1 { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string InvoiceTo { get; set; }
        public string PriceList { get; set; }
        public string Category { get; set; }
        public string SalesRep { get; set; }
        public string Delivery { get; set; }
        public string Payment { get; set; }
        public string Giro { get; set; }
        public string Tax { get; set; }
        public string TaxNo { get; set; }
        public double Balance { get; set; }
        public double CreditLimit { get; set; }
        public string Grouping { get; set; }
        public string Currency { get; set; }
        public string Language { get; set; }
        public string Interest { get; set; }
        public string Agent { get; set; }
        public string Reports { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public short Allocate { get; set; }
        public short Blocked { get; set; }
        public string Remarks { get; set; }
        public short Link { get; set; }
        public string Email { get; set; }
        public string InterNet { get; set; }
        public short EECCountry { get; set; }
        public byte EECTransCode { get; set; }
        public Nullable<System.DateTime> LastInterest { get; set; }
        public Nullable<System.DateTime> LastReminder { get; set; }
        public Nullable<System.DateTime> LastInvoice { get; set; }
        public Nullable<System.DateTime> LastPayment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public double CalcInterest { get; set; }
        public double CalcBalance { get; set; }
        public short LastReminderNo { get; set; }
        public double EndDiscPct { get; set; }
        public string Bank { get; set; }
        public string ShipTo { get; set; }
        public string Ship1 { get; set; }
        public string Ship2 { get; set; }
        public string Ship3 { get; set; }
        public string Ship5 { get; set; }
        public string Ship6 { get; set; }
        public string Ship7 { get; set; }
        public string OptionalText1 { get; set; }
        public string OptionalText2 { get; set; }
        public string OptionalText3 { get; set; }
        public string OptionalText4 { get; set; }
        public string OptionalText5 { get; set; }
        public string OptionalText6 { get; set; }
        public string OptionalText7 { get; set; }
        public string OptionalText8 { get; set; }
        public double OptionalNumber1 { get; set; }
        public double OptionalNumber2 { get; set; }
        public double OptionalNumber3 { get; set; }
        public double OptionalNumber4 { get; set; }
        public double OptionalNumber5 { get; set; }
        public double OptionalNumber6 { get; set; }
        public double OptionalNumber7 { get; set; }
        public double OptionalNumber8 { get; set; }
        public short Optional1 { get; set; }
        public short Optional2 { get; set; }
        public short Optional3 { get; set; }
        public short Optional4 { get; set; }
        public short Optional5 { get; set; }
        public short Optional6 { get; set; }
        public short Optional7 { get; set; }
        public short Optional8 { get; set; }
        public string CashDiscount { get; set; }
        public long PBSGruppeNo { get; set; }
        public long PBSAgrementNo { get; set; }
        public Nullable<System.DateTime> PBSStartDate { get; set; }
        public string OpenItemLockedBy { get; set; }
        public System.Guid GUID { get; set; }
        public string OrderCommunication { get; set; }
        public string EDILocationNr { get; set; }
        public string InternalRemarks { get; set; }
        public string LoginName { get; set; }
        public string LoginPassWord { get; set; }
        public byte AllowStatement { get; set; }
        public byte FactoringState { get; set; }
        public string FactoringGroup { get; set; }
        public string FIKNo { get; set; }
        public string CountryCode { get; set; }
        public byte IsLiableToPayTax { get; set; }
        public string ShipCityName { get; set; }
        public string ShipPostalCode { get; set; }
        public string Ship4 { get; set; }
        public string CustomerRight { get; set; }
        public Nullable<System.DateTime> OptionalDate1 { get; set; }
        public Nullable<System.DateTime> OptionalDate2 { get; set; }
        public Nullable<System.DateTime> OptionalDate3 { get; set; }
        public Nullable<System.DateTime> OptionalDate4 { get; set; }
        public Nullable<System.DateTime> OptionalDate5 { get; set; }
        public Nullable<System.DateTime> OptionalDate6 { get; set; }
        public Nullable<System.DateTime> OptionalDate7 { get; set; }
        public Nullable<System.DateTime> OptionalDate8 { get; set; }
        public string CPR { get; set; }
        public short OrderMerging { get; set; }
    }
}
