//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLink
    {
        public string Host { get; set; }
        public int TP { get; set; }
        public int LinkRecordID { get; set; }
        public bool Selected { get; set; }
        public string LinkText { get; set; }
        public Nullable<double> Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> LinkGUID { get; set; }
        public Nullable<double> Number1 { get; set; }
        public Nullable<double> Number2 { get; set; }
    }
}
