//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryFee
    {
        public string Delivery { get; set; }
        public double Amount { get; set; }
        public float Weight { get; set; }
        public float Volume { get; set; }
        public double Fee { get; set; }
        public int RecordId { get; set; }
        public byte FeeType { get; set; }
        public byte InclDuty { get; set; }
        public System.Guid GUID { get; set; }
    }
}
