//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPackFormat
    {
        public string DeliveryPackFormat1 { get; set; }
        public string DefFileName { get; set; }
        public int Automatic { get; set; }
    }
}
