//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desktop
    {
        public string Desktop1 { get; set; }
        public string Description { get; set; }
        public string Parameter { get; set; }
        public string Parameter2 { get; set; }
        public string SliderbarLinks { get; set; }
        public short Language { get; set; }
        public bool Toolbar { get; set; }
        public bool SliderBar { get; set; }
        public short SliderBarGroup { get; set; }
        public bool StatusBar { get; set; }
        public System.Guid GUID { get; set; }
    }
}
