//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsCustomer
    {
        public string Customer { get; set; }
        public int RecordID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Document { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> FileGUID { get; set; }
        public string Orderno { get; set; }
    }
}
