//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMergeSetup
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Table_name { get; set; }
        public string DocumentPath { get; set; }
        public string PrintPath { get; set; }
        public bool CreateDoc { get; set; }
        public bool PrintDoc { get; set; }
        public bool CreateLinkDoc { get; set; }
        public string SortField { get; set; }
        public System.Guid GUID { get; set; }
        public string FieldsToShow { get; set; }
    }
}
