//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePrice
    {
        public int RecordID { get; set; }
        public string Employee { get; set; }
        public string CostCenter { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public double SalesPrice { get; set; }
        public double CostPrice { get; set; }
        public System.Guid GUID { get; set; }
    }
}
