//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalData
    {
        public int RecordId { get; set; }
        public string MenuDescription { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public short Module { get; set; }
        public int SortIndex { get; set; }
        public bool OnMenu1 { get; set; }
        public bool OnMenu2 { get; set; }
        public bool OnMenu3 { get; set; }
        public string ExtraDefinition { get; set; }
        public bool OnMenu4 { get; set; }
        public System.Guid GUID { get; set; }
        public bool OnMenu5 { get; set; }
    }
}
