//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalKeyChange
    {
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string MasterTableName { get; set; }
        public string MasterColumnName { get; set; }
        public System.Guid GUID { get; set; }
    }
}
