//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraItemPrice
    {
        public int RecordID { get; set; }
        public string PriceList { get; set; }
        public short PriceType { get; set; }
        public string Item { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Active { get; set; }
        public Nullable<System.DateTime> Inactive { get; set; }
        public string ExternalNo { get; set; }
        public string Remarks { get; set; }
        public double Avance { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public System.Guid GUID { get; set; }
        public double ColiSize { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    }
}
