//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoringGroup
    {
        public string Grouping { get; set; }
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
        public string SetOff { get; set; }
        public string BankExpenses { get; set; }
        public string CashDiscount { get; set; }
        public string Correction { get; set; }
        public string Interest { get; set; }
        public string RateDif { get; set; }
        public string ReminderFee { get; set; }
    }
}
