//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid GUID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public byte[] FileData { get; set; }
        public string FileType { get; set; }
        public string Report { get; set; }
        public string URL { get; set; }
        public string Log { get; set; }
        public double Trail { get; set; }
    }
}
