//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterData
    {
        public string ID { get; set; }
        public string Description { get; set; }
        public string Info { get; set; }
        public string Criterie { get; set; }
        public string Fields { get; set; }
        public short KeepLast { get; set; }
        public string SortField { get; set; }
        public byte SortDirection { get; set; }
        public System.Guid GUID { get; set; }
        public bool ShowInMenu { get; set; }
    }
}
