//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> Link_GUID { get; set; }
        public byte[] Image1 { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public int RecordId { get; set; }
        public string ImageGroup { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
    }
}
