//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpExp
    {
        public int UnikID { get; set; }
        public string ID { get; set; }
        public short TP { get; set; }
        public string Format { get; set; }
        public bool ColNameheader { get; set; }
        public string CharacterSet { get; set; }
        public string DateTimeFormat { get; set; }
        public string DecimalSymbol { get; set; }
        public short NumberDigits { get; set; }
        public string CurrencySymbol { get; set; }
        public string TableName { get; set; }
        public string FileName { get; set; }
        public string Delimiter { get; set; }
        public string ImportTP { get; set; }
        public string StandardRec { get; set; }
        public string Description { get; set; }
        public bool UpdateRecord { get; set; }
    }
}
