//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportSetup
    {
        public string ImportID { get; set; }
        public string Fields { get; set; }
        public string Separator { get; set; }
        public string TextQualifier { get; set; }
        public string Decimal { get; set; }
        public short Format { get; set; }
        public string Date { get; set; }
        public string Filename { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string MoveToPath { get; set; }
        public System.Guid GUID { get; set; }
        public string FixedFormat { get; set; }
        public byte SP_Type { get; set; }
        public string SP_Standard { get; set; }
        public string SP_ErrorFilename { get; set; }
        public bool HasHeader { get; set; }
    }
}
