//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public string Interest1 { get; set; }
        public string Description { get; set; }
        public double Rate { get; set; }
        public short Days { get; set; }
        public double AmountDue { get; set; }
        public double Charge { get; set; }
        public string Account { get; set; }
        public string Remarks { get; set; }
        public short InterestIsCarrier { get; set; }
        public short ChargeIsCarrier { get; set; }
        public string ChargeAccount { get; set; }
        public System.Guid GUID { get; set; }
    }
}
