//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAdjustSalesprice
    {
        public string Item { get; set; }
        public string Pricelist { get; set; }
        public string Description { get; set; }
        public double Costprice { get; set; }
        public double Salesprice { get; set; }
        public double Avance { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public double NewSalesPrice { get; set; }
        public string Currency { get; set; }
        public double Rate { get; set; }
        public double StandardAvance { get; set; }
        public Nullable<double> PriceListPrice { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.DateTime> Active { get; set; }
        public Nullable<System.DateTime> Inactive { get; set; }
    }
}
