//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCountJournal
    {
        public string Journal { get; set; }
        public string FItem { get; set; }
        public string TItem { get; set; }
        public string FGrouping { get; set; }
        public string TGrouping { get; set; }
        public string FLocation { get; set; }
        public string TLocation { get; set; }
        public string FPlacement { get; set; }
        public string TPlacement { get; set; }
        public int SortField { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
        public bool Option1 { get; set; }
        public bool Option2 { get; set; }
        public bool Option3 { get; set; }
        public bool Option4 { get; set; }
        public bool Option5 { get; set; }
        public System.Guid GUID { get; set; }
        public byte OnhandMethod { get; set; }
        public string FSupplier { get; set; }
        public string TSupplier { get; set; }
    }
}
