//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemNo
    {
        public string Item { get; set; }
        public byte TP { get; set; }
        public string Customer { get; set; }
        public string Supplier { get; set; }
        public string CusSupItem { get; set; }
        public string Description { get; set; }
        public int RecordID { get; set; }
        public int DeliveryTime { get; set; }
        public System.Guid GUID { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
    }
}
