//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryArchive
    {
        public string Item { get; set; }
        public long ItemTrail { get; set; }
        public string Description { get; set; }
        public string SupplierNo { get; set; }
        public string CustomerNo { get; set; }
        public string InternalNo { get; set; }
        public string Extra { get; set; }
        public string Unit { get; set; }
        public float Weight { get; set; }
        public float Volume { get; set; }
        public double Decimals { get; set; }
        public double SalesPrice { get; set; }
        public double CostPrice { get; set; }
        public double NewCost { get; set; }
        public string Category { get; set; }
        public string Alternative { get; set; }
        public string TaxBuying { get; set; }
        public string TaxSelling { get; set; }
        public string CustomsNo { get; set; }
        public double OnHand { get; set; }
        public double OnHandPhys { get; set; }
        public double Allocated { get; set; }
        public double Ordered { get; set; }
        public double Value { get; set; }
        public double Deviation { get; set; }
        public string Grouping { get; set; }
        public string Location { get; set; }
        public string Picture { get; set; }
        public short Status { get; set; }
        public short Tracking { get; set; }
        public short Blocked { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string Placement { get; set; }
        public double Avance { get; set; }
        public short AvanceType { get; set; }
        public short AllowDiscount { get; set; }
        public short AllowFinalDiscount { get; set; }
        public short ADeliveryPacket { get; set; }
        public short PriceInclDuty { get; set; }
        public double MultiplaFaktor { get; set; }
        public short SerialTypeSale { get; set; }
        public short SerialTypeBuy { get; set; }
        public string URL { get; set; }
        public string InternetGroup { get; set; }
        public string Picture2 { get; set; }
        public string ItemEAN { get; set; }
        public string ItemAlternative { get; set; }
        public string OptionalText1 { get; set; }
        public string OptionalText2 { get; set; }
        public string OptionalText3 { get; set; }
        public string OptionalText4 { get; set; }
        public string OptionalText5 { get; set; }
        public string OptionalText6 { get; set; }
        public string OptionalText7 { get; set; }
        public string OptionalText8 { get; set; }
        public double OptionalNumber1 { get; set; }
        public double OptionalNumber2 { get; set; }
        public double OptionalNumber3 { get; set; }
        public double OptionalNumber4 { get; set; }
        public double OptionalNumber5 { get; set; }
        public double OptionalNumber6 { get; set; }
        public double OptionalNumber7 { get; set; }
        public double OptionalNumber8 { get; set; }
        public short Optional1 { get; set; }
        public short Optional2 { get; set; }
        public short Optional3 { get; set; }
        public short Optional4 { get; set; }
        public short Optional5 { get; set; }
        public short Optional6 { get; set; }
        public short Optional7 { get; set; }
        public short Optional8 { get; set; }
        public double TmpOnHand { get; set; }
        public double TmpValue { get; set; }
        public double DefaultQuantity { get; set; }
        public short AllocateBOMItems { get; set; }
        public double LastCostPercentAmount { get; set; }
        public short NewCostStatus { get; set; }
        public double PriceIncl { get; set; }
        public double SalesUnit { get; set; }
        public byte CostPriceAdjustment { get; set; }
        public byte PostServiceCostPrice { get; set; }
        public int DeliveryTime { get; set; }
        public byte KeepPriceOnOrdreRecalc { get; set; }
        public double QuantityPrColi { get; set; }
        public double Available { get; set; }
        public System.Guid GUID { get; set; }
        public byte WebUseOnWeb { get; set; }
        public byte WebHasNews { get; set; }
        public byte WebIsDiscount { get; set; }
        public string ItemRight { get; set; }
        public string ProvisionGroup { get; set; }
        public short UseSalesUnitInfo { get; set; }
        public string WebTitle { get; set; }
        public string WebAlt { get; set; }
        public string WebMetaTags { get; set; }
        public string WebMetaDescription { get; set; }
    }
}
