//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPriceImportSetup
    {
        public string ImportFormat { get; set; }
        public string ControlID { get; set; }
        public string ControlStringValue { get; set; }
        public int ControlIntValue { get; set; }
        public double ControlFloatValue { get; set; }
        public System.Guid GUID { get; set; }
    }
}
