//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPriceImport
    {
        public string Item { get; set; }
        public bool DeleteState { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<double> SalesPrice { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> Avance { get; set; }
        public string Grouping { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NewSalesPrice { get; set; }
        public Nullable<double> NewCostPrice { get; set; }
        public byte UpdateStatus { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
        public string ItemAlternative { get; set; }
        public string Placement { get; set; }
        public string EANItemNo { get; set; }
        public Nullable<double> QuantityPrColi { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Discount_msg { get; set; }
        public string ImportFormat { get; set; }
        public string Remarks { get; set; }
        public string InternalNo { get; set; }
    }
}
