//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBudget
    {
        public int BudgetYear { get; set; }
        public string Item { get; set; }
        public string Location { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public bool UsedLocation { get; set; }
        public bool UsedParameter1 { get; set; }
        public bool UsedParameter2 { get; set; }
        public double January { get; set; }
        public double February { get; set; }
        public double March { get; set; }
        public double April { get; set; }
        public double May { get; set; }
        public double June { get; set; }
        public double July { get; set; }
        public double August { get; set; }
        public double September { get; set; }
        public double October { get; set; }
        public double November { get; set; }
        public double December { get; set; }
        public double Quarter1 { get; set; }
        public double Quarter2 { get; set; }
        public double Quarter3 { get; set; }
        public double Quarter4 { get; set; }
        public double HalfYear1 { get; set; }
        public double HalfYear2 { get; set; }
        public double Yearly { get; set; }
        public System.Guid GUID { get; set; }
    }
}
