//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryGroup
    {
        public string Grouping { get; set; }
        public string Name { get; set; }
        public string Sales { get; set; }
        public string SalesEEC { get; set; }
        public string SalesNotEEC { get; set; }
        public string Discount { get; set; }
        public string Cost { get; set; }
        public string Deviation { get; set; }
        public string Adjustment { get; set; }
        public string AdjSetOff { get; set; }
        public string Purchase { get; set; }
        public string Stock { get; set; }
        public string Remarks { get; set; }
        public double Avance { get; set; }
        public string CostPercent { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public System.Guid GUID { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public string Discount_Buy { get; set; }
    }
}
