//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryLocationWorksheet
    {
        public string Journal { get; set; }
        public string Item { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public double Quantity { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public int RecordId { get; set; }
        public string Description { get; set; }
        public short Error { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
