//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvWorksheetSerialNo
    {
        public System.Guid LinesEntry_GUID { get; set; }
        public string SerialNo { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Optional4 { get; set; }
        public string Optional5 { get; set; }
        public string Optional6 { get; set; }
        public string Optional7 { get; set; }
        public string Optional8 { get; set; }
        public string Optional9 { get; set; }
        public string Optional10 { get; set; }
        public string Remarks { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
    }
}
