//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSerialNoTmp
    {
        public string Item { get; set; }
        public string SerialNo { get; set; }
        public string Supplier { get; set; }
        public string PurchaseNo { get; set; }
        public int PurLineRecordID { get; set; }
        public bool IsDelivered { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> LinkReceiptGUID { get; set; }
    }
}
