//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPriceAvanceGroup
    {
        public int RecordID { get; set; }
        public string PriceList { get; set; }
        public short PriceType { get; set; }
        public string InventoryGroup { get; set; }
        public double Avance { get; set; }
        public System.Guid GUID { get; set; }
        public short AvanceOption { get; set; }
    }
}
