//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSerialNo
    {
        public string Item { get; set; }
        public string SerialNo { get; set; }
        public short TP { get; set; }
        public string Supplier { get; set; }
        public string PurchaseNo { get; set; }
        public double Trail { get; set; }
        public int PurLineRecordID { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Optional4 { get; set; }
        public string Optional5 { get; set; }
        public string Optional6 { get; set; }
        public string Optional7 { get; set; }
        public string Optional8 { get; set; }
        public string Optional9 { get; set; }
        public string Optional10 { get; set; }
        public string Remarks { get; set; }
        public short LinkTP { get; set; }
        public bool IsDelivered { get; set; }
        public System.Guid GUID { get; set; }
        public short Status { get; set; }
        public double StatusTrail { get; set; }
        public Nullable<System.Guid> LinkReceiptGUID { get; set; }
    }
}
