//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSerialNoSale
    {
        public string Item { get; set; }
        public string SerialNo { get; set; }
        public short InvoiceTP { get; set; }
        public string Customer { get; set; }
        public string OrderNo { get; set; }
        public double Trail { get; set; }
        public int OrdLineRecordID { get; set; }
        public bool IsDelivered { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> LinkDeliveredGUID { get; set; }
    }
}
