//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesEntryArchive
    {
        public string Journal { get; set; }
        public string OrderNo { get; set; }
        public string PurchaseNo { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public string Item { get; set; }
        public string Location { get; set; }
        public double Ordered { get; set; }
        public double Deliver { get; set; }
        public string Unit { get; set; }
        public double Conversion { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public double Amount { get; set; }
        public string Currency { get; set; }
        public double Rate { get; set; }
        public double AmountBase { get; set; }
        public string Tax { get; set; }
        public double Delivered { get; set; }
        public double Invoiced { get; set; }
        public string ExternalNo { get; set; }
        public string BatchNo { get; set; }
        public string Customer { get; set; }
        public string Supplier { get; set; }
        public string Voucher { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public string OldOrderNo { get; set; }
        public double Quantity { get; set; }
        public double CostPrice { get; set; }
        public short Error { get; set; }
        public int RecordId { get; set; }
        public string RemarksBefore { get; set; }
        public string RemarksAfter { get; set; }
        public short AllowDiscount { get; set; }
        public short AllowFinalDiscount { get; set; }
        public bool Selected { get; set; }
        public float Weight { get; set; }
        public float Volume { get; set; }
        public short ADeliveryPacket { get; set; }
        public string CustomsNo { get; set; }
        public double DutyAmount { get; set; }
        public double DutyAmountBase { get; set; }
        public string RefOrderNo { get; set; }
        public string RefPurchaseNo { get; set; }
        public double MultiplaFaktor { get; set; }
        public int MasterID { get; set; }
        public string Account { get; set; }
        public short Status { get; set; }
        public string Employee { get; set; }
        public short LineNo { get; set; }
        public short FixedLine { get; set; }
        public double CostPercent { get; set; }
        public int TmpLong { get; set; }
        public bool InternalLine { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public short AllowDuty { get; set; }
        public double NewSalesPrice { get; set; }
        public double DeliverQuantity { get; set; }
        public double InvoiceQuantity { get; set; }
        public int BOMLineID { get; set; }
        public byte SplitStatus { get; set; }
        public double LastDelivered { get; set; }
        public double BackOrderQuantity { get; set; }
        public double QuantityPrColi { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public int JobNo { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid Link_GUID { get; set; }
        public Nullable<System.Guid> PhysicalDeliveredGUID { get; set; }
        public double PhysicalDelivered { get; set; }
    }
}
