//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesEntryBillOfMaterial
    {
        public string OrderNo { get; set; }
        public int LineID { get; set; }
        public int RecordId { get; set; }
        public int LineNo { get; set; }
        public string Master { get; set; }
        public int ParentID { get; set; }
        public int ChildID { get; set; }
        public string Item { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public string Location { get; set; }
        public string Reference { get; set; }
        public double Time { get; set; }
        public string Process { get; set; }
        public string Description { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public double Conversion { get; set; }
        public bool Deleted { get; set; }
        public double Price { get; set; }
        public double CostPrice { get; set; }
        public short AllocateState { get; set; }
        public bool DataChanged { get; set; }
        public string SerialNo { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public double Faktor { get; set; }
        public bool IsProduced { get; set; }
        public System.Guid GUID { get; set; }
        public long ItemTrail { get; set; }
    }
}
