//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeargedDiscount
    {
        public string MeargedDiscount1 { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public double Amount { get; set; }
        public bool TaxIncl { get; set; }
        public Nullable<System.DateTime> Active { get; set; }
        public Nullable<System.DateTime> InActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    }
}
