//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiDataAccountMap
    {
        public int MultiDataAccount { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public System.Guid GUID { get; set; }
        public string SalaryPeriod { get; set; }
        public byte AccountDC { get; set; }
        public string Account2 { get; set; }
        public byte Account2DC { get; set; }
        public string Account3 { get; set; }
        public byte Account3DC { get; set; }
    }
}
