//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnHand
    {
        public string Item { get; set; }
        public string Location { get; set; }
        public double OnHand1 { get; set; }
        public double OnHandPhys { get; set; }
        public double Allocated { get; set; }
        public double Ordered { get; set; }
        public double Minimum { get; set; }
        public double Maximum { get; set; }
        public double OrderSize { get; set; }
        public Nullable<System.DateTime> LastCountDate { get; set; }
        public string LastCountedOf { get; set; }
        public double LastCounted { get; set; }
        public int RecordId { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public string Placement { get; set; }
        public double Available { get; set; }
        public System.Guid GUID { get; set; }
    }
}
