//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public string Module { get; set; }
        public string OptionID { get; set; }
        public short ControlType { get; set; }
        public string Selection { get; set; }
        public string Value { get; set; }
        public string DropTag { get; set; }
        public string Value1 { get; set; }
        public System.Guid GUID { get; set; }
    }
}
