//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders2
    {
        public System.Guid GUID { get; set; }
        public System.Guid LinkGUID { get; set; }
        public string OrderNo { get; set; }
        public bool WPA_Activated { get; set; }
        public byte WPA_Prioritet { get; set; }
        public Nullable<System.DateTime> WPA_StartDate { get; set; }
        public Nullable<System.DateTime> WPA_EndDate { get; set; }
        public bool WPA_Type { get; set; }
        public short WPA_Status { get; set; }
        public Nullable<System.DateTime> WPA_LastSend { get; set; }
        public short WPA_LastStatus { get; set; }
        public Nullable<System.DateTime> eLPc_StartDate { get; set; }
        public Nullable<System.DateTime> eLPc_EndDate { get; set; }
        public short eLPc_AdmJobnr { get; set; }
        public short eLPc_JobFinished { get; set; }
        public long WPA_WorkCard { get; set; }
        public string WPA_Employee { get; set; }
        public string WPA_Department { get; set; }
        public bool WPA_IncludeNoLines { get; set; }
        public string WPA_Description { get; set; }
        public string WPA_CRMInfo1 { get; set; }
        public string WPA_CRMInfo2 { get; set; }
    }
}
