//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodBalance
    {
        public string Account { get; set; }
        public Nullable<System.DateTime> Ending { get; set; }
        public short Opening { get; set; }
        public string Name { get; set; }
        public double Budget { get; set; }
        public double Balance { get; set; }
        public double Quantity { get; set; }
        public string Remarks { get; set; }
        public double SystemBalance { get; set; }
        public string PeriodID { get; set; }
        public System.Guid GUID { get; set; }
    }
}
