//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public string PriceList1 { get; set; }
        public string Name { get; set; }
        public short PriceType { get; set; }
        public string Remarks { get; set; }
        public double Avance { get; set; }
        public string Currency { get; set; }
        public System.Guid GUID { get; set; }
        public short AvanceOption { get; set; }
        public short AllowUpdateFromPriceImport { get; set; }
        public double IndexLastYear { get; set; }
        public double IndexThisYear { get; set; }
        public short RoundPrice { get; set; }
    }
}
