//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureLock
    {
        public int RecordID { get; set; }
        public string ReminderProcedure { get; set; }
        public string InterestProcedure { get; set; }
        public string OrderBatchProcedure { get; set; }
        public string OrderSubBatchProcedure { get; set; }
        public string AdjustInventoryProcedure { get; set; }
        public string GeneratePurchasesProcedure { get; set; }
        public string InventoryPriceImport { get; set; }
        public System.Guid GUID { get; set; }
    }
}
