//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCalculationLine
    {
        public int RecordId { get; set; }
        public string CalculationName { get; set; }
        public byte LineType { get; set; }
        public int LineNo { get; set; }
        public string Project { get; set; }
        public string CostCenter { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public double CostPrice { get; set; }
        public double Price { get; set; }
        public double Avance { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
    }
}
