//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSubProject
    {
        public string Project { get; set; }
        public string SubProject { get; set; }
        public string Remarks { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
    }
}
