//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGroup
    {
        public string Grouping { get; set; }
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
        public string Aconto { get; set; }
        public string MoreSale { get; set; }
        public string ActivatingAccount { get; set; }
        public bool IsStandard { get; set; }
        public string AcontoReportGroup { get; set; }
        public string MoreSaleReportGroup { get; set; }
    }
}
