//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provision
    {
        public string ProvisionGroup { get; set; }
        public string Employee { get; set; }
        public System.DateTime Date { get; set; }
        public double MaxDiscountPct { get; set; }
        public double Provision1 { get; set; }
        public System.Guid GUID { get; set; }
    }
}
