//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseImport
    {
        public string LayoutID { get; set; }
        public string Description { get; set; }
        public bool UseLayout { get; set; }
        public string FileName { get; set; }
        public bool DeleteAfterImport { get; set; }
        public string CopyToPath { get; set; }
        public byte DefaultItemAccountType { get; set; }
        public string DefaultItemAccount { get; set; }
        public int RecordID { get; set; }
        public string Supplier { get; set; }
        public System.Guid GUID { get; set; }
        public byte GroupAccount { get; set; }
        public byte LayoutType { get; set; }
        public bool TrimLeadingZerosItemNo { get; set; }
        public bool TrimLeadingZerosOther { get; set; }
        public string DefaultDutyAccount { get; set; }
        public string DefaultFeeAccount { get; set; }
        public bool CreateOrderLines { get; set; }
        public string DefaultDiscountAccount { get; set; }
        public bool ConvertAfterItemsSalesUnit { get; set; }
        public string UseColiFromPricelist { get; set; }
        public string DefaultPath { get; set; }
    }
}
