//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseLog
    {
        public string PurchaseNo { get; set; }
        public double Trail { get; set; }
        public string Description { get; set; }
        public string Voucher { get; set; }
        public string Report { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> FileGUID { get; set; }
        public System.Guid GUID { get; set; }
        public string Employee { get; set; }
        public string Remarks { get; set; }
    }
}
