//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemindersSetup
    {
        public int RecordID { get; set; }
        public double ReminderFee1 { get; set; }
        public double ReminderFee2 { get; set; }
        public double ReminderFee3 { get; set; }
        public double ReminderFee4 { get; set; }
        public short Waitingdays1 { get; set; }
        public short Waitingdays2 { get; set; }
        public short Waitingdays3 { get; set; }
        public short Waitingdays4 { get; set; }
        public bool FeeInclTax { get; set; }
        public double MinAmount { get; set; }
        public string Report { get; set; }
        public string Source { get; set; }
        public string Tax { get; set; }
        public bool Skip1 { get; set; }
        public bool Skip2 { get; set; }
        public bool Skip3 { get; set; }
        public bool Skip4 { get; set; }
        public short BlockCustomerLevel { get; set; }
        public bool AllRemindersAtSameLevel { get; set; }
        public System.Guid GUID { get; set; }
    }
}
