//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public string Customer { get; set; }
        public decimal Amount { get; set; }
        public short ReminderNo { get; set; }
        public string Voucher { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public string Description { get; set; }
        public decimal OpenAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public string Header { get; set; }
        public string RemText { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> DueByDate { get; set; }
        public short LastReminderNo { get; set; }
        public Nullable<System.DateTime> LastReminder { get; set; }
        public string Payment { get; set; }
        public System.Guid GUID { get; set; }
    }
}
