//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportUserOption
    {
        public int Recordid { get; set; }
        public string Report { get; set; }
        public short Module { get; set; }
        public string UserName { get; set; }
        public string Printer { get; set; }
        public short Copies { get; set; }
        public short FirstCopyTray { get; set; }
        public short OtherCopiesTray { get; set; }
        public byte PreViewFormat { get; set; }
        public System.Guid GUID { get; set; }
    }
}
