//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sigma
    {
        public int id { get; set; }
        public string position { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string unit { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> unitprice { get; set; }
        public Nullable<double> costprice { get; set; }
        public Nullable<double> salesunitprice { get; set; }
        public Nullable<double> salesprice { get; set; }
        public Nullable<double> coverage { get; set; }
        public string note { get; set; }
        public string flag { get; set; }
        public string project_number { get; set; }
        public string item_number { get; set; }
        public string supplier_number { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public System.Guid GUID { get; set; }
    }
}
