//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSMessage
    {
        public int RecordId { get; set; }
        public string Mobile { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public string MainKey { get; set; }
        public string UserName { get; set; }
        public System.Guid GUID { get; set; }
    }
}
