//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContact
    {
        public string Supplier { get; set; }
        public int RecordID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string LocalNumber { get; set; }
        public string DirectPhone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string InterNet { get; set; }
        public System.Guid GUID { get; set; }
        public bool InquiryReportFlags { get; set; }
        public bool RequisitionReportFlags { get; set; }
        public bool ReceiptReportFlags { get; set; }
    }
}
