//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierReport
    {
        public string Reports { get; set; }
        public string Inquiry { get; set; }
        public string Requisition { get; set; }
        public string Receipt { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
        public string Invoice { get; set; }
        public string CreditNote { get; set; }
    }
}
