//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBankData
    {
        public string Supplier { get; set; }
        public bool Selected { get; set; }
        public bool SumTrans { get; set; }
        public Nullable<System.DateTime> SumPayDate { get; set; }
        public double SumPayAmount { get; set; }
        public string RegNo { get; set; }
        public string AccountNo { get; set; }
        public string SenderAdviseText { get; set; }
        public string CustomerID { get; set; }
        public short TransferType { get; set; }
        public string BankName { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string BankAddress3 { get; set; }
        public string SWIFTAddress { get; set; }
        public string BankISOCountry { get; set; }
        public string BankCode { get; set; }
        public int BankNo { get; set; }
        public short Cost { get; set; }
        public string BankText { get; set; }
        public string PaymentCategory { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public byte ReportType { get; set; }
        public string ReportText { get; set; }
        public byte CheckCrosses { get; set; }
        public short CheckSend { get; set; }
        public bool AmountIncludesCost { get; set; }
        public byte RateType { get; set; }
        public short Branch { get; set; }
        public string RecipientName { get; set; }
        public string RecipientAddress1 { get; set; }
        public string RecipientAddress2 { get; set; }
        public string RecipientAddress3 { get; set; }
        public byte PaymentTP { get; set; }
        public string ISOCountry { get; set; }
        public byte RecipientNotificationType { get; set; }
        public bool SupplierDataOK { get; set; }
        public bool SupplierDataEdited { get; set; }
        public System.Guid GUID { get; set; }
        public string Templet { get; set; }
        public string Giro { get; set; }
        public string FIKNumber { get; set; }
        public string IBAN { get; set; }
    }
}
