//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierGroup
    {
        public string Grouping { get; set; }
        public string Name { get; set; }
        public string Purchase { get; set; }
        public string Discount { get; set; }
        public string Deviation { get; set; }
        public string Payable { get; set; }
        public string SetOff { get; set; }
        public string Remarks { get; set; }
        public string CostPercent { get; set; }
        public string ObtainedDiscount { get; set; }
        public string FeeInclVAT { get; set; }
        public string FeeExclVat { get; set; }
        public string ObtainedCashDiscount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public System.Guid GUID { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
    }
}
