//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public string Tax1 { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public short ReturnCode { get; set; }
        public string Balance { get; set; }
        public string Aquisition { get; set; }
        public double Ratio { get; set; }
        public string Expenses { get; set; }
        public string Remarks { get; set; }
        public short Link { get; set; }
        public System.Guid GUID { get; set; }
        public string EECServiceTax { get; set; }
        public int ReverseTax { get; set; }
    }
}
