//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxPeriod
    {
        public System.DateTime Starting { get; set; }
        public Nullable<System.DateTime> Ending { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public Nullable<System.DateTime> Printed { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string Remarks { get; set; }
        public short Link { get; set; }
        public System.Guid GUID { get; set; }
    }
}
