//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempBalance
    {
        public string UserId { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public short Type { get; set; }
        public string SetOff { get; set; }
        public double Balance1 { get; set; }
        public double BalanceYTD { get; set; }
        public double BalanceL1 { get; set; }
        public double BalanceLYTD { get; set; }
        public System.Guid GUID { get; set; }
    }
}
