//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeManager
    {
        public string Customer { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string Remarks { get; set; }
        public string OrderNo { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
        public string Item { get; set; }
    }
}
