//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeHeaderLine
    {
        public System.Guid GUID { get; set; }
        public string Employee { get; set; }
        public string Project { get; set; }
        public string CostCenter { get; set; }
        public string Department { get; set; }
        public string Purpose { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
