//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransOpenItem
    {
        public int TransRef { get; set; }
        public int EntryRef { get; set; }
        public int SettleRef { get; set; }
        public Nullable<System.DateTime> SettledDate { get; set; }
        public double TransAmount { get; set; }
        public double TransAmountBase { get; set; }
        public double Difference { get; set; }
        public System.Guid GUID { get; set; }
    }
}
