//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransInterestItem
    {
        public int TransRef { get; set; }
        public int SettelRef { get; set; }
        public double Interest { get; set; }
        public string Customer { get; set; }
        public System.Guid GUID { get; set; }
    }
}
