//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormPosition
    {
        public string UserName { get; set; }
        public string FormName { get; set; }
        public short State { get; set; }
        public short Top { get; set; }
        public short Left { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public string Desktop { get; set; }
        public string GridInfo { get; set; }
        public System.Guid GUID { get; set; }
        public string SortField { get; set; }
        public string ToolBar { get; set; }
        public byte Version { get; set; }
    }
}
