//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public string UserName { get; set; }
        public string SupAuthBank { get; set; }
        public Nullable<System.DateTime> TransExportFromDate { get; set; }
        public Nullable<System.DateTime> TransExportToDate { get; set; }
        public string TransExportFileName { get; set; }
        public string TransExportEMail { get; set; }
        public System.Guid GUID { get; set; }
    }
}
