//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormGridSetup
    {
        public string UserName { get; set; }
        public string FormName { get; set; }
        public short GridType { get; set; }
        public string GridName { get; set; }
        public int RowHeight { get; set; }
        public string Columns { get; set; }
        public string NoViewColumns { get; set; }
        public System.Guid GUID { get; set; }
    }
}
