//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFormTabIndex
    {
        public string UserName { get; set; }
        public string FormName { get; set; }
        public string ControlName { get; set; }
        public int Index { get; set; }
        public int TabIndex { get; set; }
        public System.Guid GUID { get; set; }
    }
}
