//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLastViewRecord
    {
        public string UserName { get; set; }
        public short Module { get; set; }
        public string KeyValue1 { get; set; }
        public string KeyValue2 { get; set; }
        public System.Guid GUID { get; set; }
    }
}
