//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccountingYearInfo
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> Beginning { get; set; }
        public Nullable<System.DateTime> Ending { get; set; }
        public int Periods { get; set; }
        public string YearPrimoID { get; set; }
        public string YearUltimoID { get; set; }
        public string YearFirstPeriodID { get; set; }
        public string YearLastPeriodID { get; set; }
        public string AccountingYearDescription { get; set; }
    }
}
