//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDepartmentPeriodBalance
    {
        public string Account { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Opening { get; set; }
        public string PeriodID { get; set; }
        public string Department { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
