//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventoryParameter1
    {
        public string Item { get; set; }
        public short ParamNo { get; set; }
        public string Parameter { get; set; }
        public short SortIndex { get; set; }
        public System.Guid GUID { get; set; }
    }
}
