//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public string Voucher1 { get; set; }
        public string Description { get; set; }
        public double Next { get; set; }
        public double Minimum { get; set; }
        public double Maximum { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
    }
}
