//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPriceImport
    {
        public string Solar { get; set; }
        public string Louis_Poulsen { get; set; }
        public string Sanistål { get; set; }
        public string Sanistål__Layout_75_ { get; set; }
        public string Brødrene_Dahl { get; set; }
        public string Brødrene_A__og_O__Johansen { get; set; }
        public string C_Komplet__Brødrene_A__og_O__Johansen { get; set; }
        public string DDT___Prisbog_2_BFCs_format { get; set; }
        public string Otra { get; set; }
        public string Grene { get; set; }
        public string Cubic { get; set; }
        public string W_M__Electro { get; set; }
        public string Tridan { get; set; }
        public string EL_Salg { get; set; }
        public string Ahlsell_Danmark_A_S { get; set; }
        public string P__Henning_Jensen { get; set; }
        public string A__C__Nielsen { get; set; }
        public string Jens_A__Jacobsen_AS { get; set; }
        public string LMB { get; set; }
        public string LMG { get; set; }
        public string MECA { get; set; }
        public string Ruko { get; set; }
        public string Copiax { get; set; }
        public string Actebis { get; set; }
        public string In_and_Out { get; set; }
    }
}
