//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReminderLevel
    {
        public int ReminderLevel { get; set; }
        public double Fee { get; set; }
        public short WaitingDays { get; set; }
        public bool Skip { get; set; }
    }
}
