//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeterEntry
    {
        public string WaterMeter { get; set; }
        public string Customer { get; set; }
        public string Item { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public double SalesPrice { get; set; }
        public double Amount { get; set; }
        public double Open { get; set; }
        public string Tax { get; set; }
        public short SplitLine { get; set; }
        public string OrderNo { get; set; }
        public byte Month { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsStatement { get; set; }
        public string StatementOrderNo { get; set; }
        public Nullable<bool> IsConsume { get; set; }
        public short LineNo { get; set; }
        public int RecordId { get; set; }
        public int ProcedureTrail { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
        public bool IsInfo { get; set; }
        public double MeterLevel { get; set; }
    }
}
