//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeterWorkSheetLog
    {
        public string Customer { get; set; }
        public string WaterMeter { get; set; }
        public System.Guid ItemGUID { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public double QuantityBefore { get; set; }
        public double QuantityAfter { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.Guid GUID { get; set; }
        public double MeterLevelBefore { get; set; }
        public double MeterLevelAfter { get; set; }
    }
}
