//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeterItem
    {
        public string WaterMeter { get; set; }
        public string Customer { get; set; }
        public string Item { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public double SalesPrice { get; set; }
        public double NextSalesPrice { get; set; }
        public string Tax { get; set; }
        public short SplitLine { get; set; }
        public short IsConsume { get; set; }
        public short LineNo { get; set; }
        public int RecordId { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
        public double MeterLevel { get; set; }
        public double NextQuantity { get; set; }
        public string NextAccount { get; set; }
    }
}
