//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeterLog
    {
        public int ProcedureTrail { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public short Periode { get; set; }
        public bool IsReturne { get; set; }
        public short OptionType { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
    }
}
