//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeter
    {
        public string WaterMeter1 { get; set; }
        public string Customer { get; set; }
        public bool IsActiv { get; set; }
        public bool Month1 { get; set; }
        public bool Month2 { get; set; }
        public bool Month3 { get; set; }
        public bool Month4 { get; set; }
        public bool Month5 { get; set; }
        public bool Month6 { get; set; }
        public bool Month7 { get; set; }
        public bool Month8 { get; set; }
        public bool Month9 { get; set; }
        public bool Month10 { get; set; }
        public bool Month11 { get; set; }
        public bool Month12 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public Nullable<System.DateTime> Date9 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public Nullable<System.DateTime> Date11 { get; set; }
        public Nullable<System.DateTime> Date12 { get; set; }
        public Nullable<System.DateTime> TakeDownDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string LandRegisterNo { get; set; }
        public string Remarks { get; set; }
        public int RecordId { get; set; }
        public System.Guid GUID { get; set; }
        public short OptionType1 { get; set; }
        public short OptionType2 { get; set; }
        public short OptionType3 { get; set; }
        public short OptionType4 { get; set; }
        public short OptionType5 { get; set; }
        public short OptionType6 { get; set; }
        public short OptionType7 { get; set; }
        public short OptionType8 { get; set; }
        public short OptionType9 { get; set; }
        public short OptionType10 { get; set; }
        public short OptionType11 { get; set; }
        public short OptionType12 { get; set; }
        public string OldCustomer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
