//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterMeterWorkSheet
    {
        public string Customer { get; set; }
        public string WaterMeter { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public double Quantity { get; set; }
        public string Remarks { get; set; }
        public System.Guid GUID { get; set; }
        public int RecordId { get; set; }
        public System.Guid ItemGUID { get; set; }
        public double OrgQuantity { get; set; }
        public int Error { get; set; }
        public double OrgMeterLevel { get; set; }
        public double NewMeterLevel { get; set; }
        public string Journal { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
